### ISSUE TITLE
Adding the One-dark theme ?

### ISSUE THREAD

**Issue by MrLixm** [JonBunator/gitkraken-custom-themes#15]
Hello, first awesome initiative !

Just a suggestion for adding the famous One-Dark theme to the list :
> https://github.com/one-dark/jetbrains-one-dark-theme#readme

Even though it seems the theme doesn't apply to the code editor ? Which is the main reason I would use One-Dark.

Cheers.
Liam.

**Comment by JonBunator** [comment]
Thanks for the suggestions! I'll add it :)

> Even though it seems the theme doesn't apply to the code editor ? Which is the main reason I would use One-Dark.

The code editor changes its background color since v8.3.0
But the syntax highlighting is not changeable unfortunately
For example:
Nord:
![grafik](https://user-images.githubusercontent.com/62108893/157394732-ff4dbaa4-dd13-4ac8-9a94-be3ddf3be1b7.png)

VS Default:
![grafik](https://user-images.githubusercontent.com/62108893/157394781-e732face-49de-42ec-9b9e-2056d0f7b9d8.png)

**Comment by MrLixm** [comment]
Thanks for confirming, I will wait till they add support for it then !

**Comment by MrLixm** [comment]
That's awesome, thanks a lot ! working fine on my side
